source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 3.1.0"

gem 'cocoapods', '>= 1.16.2'
gem 'activesupport', '>= 7.1.3'

# Ruby 3.4 removed these from the standard library.
gem 'bigdecimal'
gem 'logger'
gem 'benchmark'
gem 'mutex_m'
gem 'nkf'
